### ISSUE TITLE
Paper link is empty

### ISSUE THREAD

**Issue by wawcac** [2017211801/SemanticHuman#1]
Dear authors,
I noticed that the paper link mentioned in the README file of this repository is empty. I am very interested in this paper and would like to read it. Could you please provide the link to the paper or other ways to access it?

Thank you very much!

**Comment by 2017211801** [comment]
> Dear authors, I noticed that the paper link mentioned in the README file of this repository is empty. I am very interested in this paper and would like to read it. Could you please provide the link to the paper or other ways to access it?
> 
> Thank you very much!

Hello! I'm very sorry for not updating the homepage in time due to my negligence, we will update the homepage with the paper next week, thank you for your attention!
