### ISSUE TITLE
About the conversion between SemanticHuman and SMPL

### ISSUE THREAD

**Issue by Hao-hui** [2017211801/SemanticHuman#2]
Good job! Your proposal for a new representation of the human body is very intriguing. May I ask if you could provide a convenient way to quickly convert the parameters of SMPL (θ and β) and the bone orientation, bone length and shape parameters of your constructed representation model?

**Comment by 2017211801** [comment]
Hello, as we introduced in our paper, we proposed a new decoupling idea different from smpl, so it is a pity that we cannot directly convert the model parameters; but you can use the encoder to obtain ours parameters of meshes generated by smpl.
